# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - detail_blocks
  label: "YouTube Video"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Video Title
  description: Video description.
  video_id: EMhV-NvxrAo

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: