# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Tabs"
  description:
  icon: tabs
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  tabs:
    - label: Tab 1
      text: Tab 1 text.
    - label: Tab 2
      text: Tab 2 text.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: