# Metadata about this component, to be used in the CMS
spec:
  structures:
    - organization_topper
  label: "Topper - Organization"
  description:
  icon: crown
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  subheading:
  use_large_background: false
  styles:
    vibe: down-to-business
    background_c:
    heading_c:
    enable_blend: true
    enable_pattern: false
    tint_opacity: 0.5
    margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  use_large_background:
    type: switch