# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero - Alysha"
  description: A simple jumbotron-style component for calling extra attention to featured content or information
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: hero-1
  heading:
    text: "IT STARTS NOW"
    hierarchy: h1
  body_text: This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
  button:
  background_image: https://designsystemv2demo.sandbox.wvu.edu/files/e4742958-d585-48b8-ade6-7f45ab929897/1780x1780?cb=e85e7133d3b969f2d6ad263a5f8a5051
  content_alignment: left

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_alignment:
    comment: Select the alignment for the box that contains the content
    type: choice
    options:
      allow_empty: false
      values:
        - name: Left
          id: left
          icon: align_horizontal_left
        - name: Center
          id: center
          icon: format_align_center
        - name: Right
          id: right
          icon: align_horizontal_right
  hierarchy:
    type: select
    options:
      values:
        - h1
        - h2
  body_text:
    type: textarea
