# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Author Bio"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  authors:
    - name: Firstname Lastname
      thumbnail: https://placehold.co/900x600
      thumbnail_alt: Placeholder
      title: Title
      tease: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.
      link:
        text: 
        url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
