# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Alumni Profile"
  description:
  icon: person
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  name: Firstname Lastname
  image:
  is_cutout: false
  label:
    - Label
  info:
    - Morgantown, WV
  ctas:
    - text: Call to Action
      url:
      icon:
    - text: Call to Action
      url:
      icon: 
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_cutout:
    type: switch