# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - content_blocks
  label: "Columns"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  heading: Test Heading
  columns:
    - column_blocks: [bookshop:structure:column_blocks]
      layout:
        column_widths:
          xxxl:
          xxl:
          xl:
          lg:
          md:
          sm: col
        text_align: text-center
    - column_blocks: [bookshop:structure:column_blocks]
      layout:
        column_widths:
          xxxl:
          xxl:
          xl:
          lg:
          md:
          sm: col
        text_align: text-center
  postscript: Test Postscript
  config:
    edit_mode_only: false
  layout:
    padding:
    justify_content: justify-content-center
    gutters:
      xxl: gx-10
  styles:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
