# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - detail_blocks
  label: "Link List Panels"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  list_description:
  items:
    - text:
      description:
      url: 
      icon:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  list_description:
    type: markdown
  icon:
    type: select
    options:
      values:
        - PDF
        - Download
        - Link