# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Column Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  elements:
    super_heading:
      label:
      text:
    heading:
    subheading:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
