# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Columns 2-1"
  description:
  icon: doc_to_right
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  column_a:
  column_b:
  config:
    edit_mode_only: false
  layout:
  styles:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
