# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Poster"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name: poster-split
  poster_image:
  alt_text:
  heading:
    - Heading Line 1
    - Heading Line 2
  body:
    - Lede.
    - Body.
  ctas:
    - text: Call to Action
      url:
      icon: arrow-circle-right
  postscript_links:
    - text: 
      url:
      icon:
  config:
    edit_mode_only: false
    is_main: 
    id:
    aria_labelledby:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
