# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - topper
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading: Heading
  body:
    - Lede.
    - Body.
  ctas:
    - text: Call to Action
      url:
      icon: arrow-circle-right
  postscript_links:
  config:
    edit_mode_only: false
    id:
  styles:
    styles_section:
    styles_h2:
    styles_h2_label:
    styles_lead:
    styles_buttons:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
