# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Big Search"
  description:
  icon: crown
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading:
    - text: Heading
  subheading: Subheading.
  placeholder:
  vibe: down_to_business
  background_c: bg-dark text-white
  heading_c:
  background_layers:
    img_blend_mode:
    img_opacity: .4
    pattern: 
    pattern_c: bg-white
    pattern_opacity: .2
    tint_opacity:
    texture: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  placeholder: