# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  profiles:
    - person:
      name: Firstname Lastname
      heading: Heading
      quote: Quote.
      thumbnail:
      thumbnail_alt:
      also_see:
        - url:
          text:
          ref:
      show: 2024-09-01
      hide: 2030-09-01
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: