# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Accordion"
  description:
  icon: top_panel_open
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  panels:
    - title: Panel 1 Title
      panel_text: Panel 1 text.
    - title: Panel 2 Title
      panel_text: Panel 2 text.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  panel_text:
    type: markdown