# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Heading"
  description: A heading with configurable hierarchies - to be used inside other components
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Heading text"
  hierarchy: h1
  name:
  bar_location:
  classes:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  bar_location: 
    type: select
    options:
      values:
        - bottom
        - top
  hierarchy:
    type: select
    options:
      values:
        - h1
        - h2
