# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Link Lists"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  heading: Heading
  subheading:
  lists:
    - topic:
      description:
      items:
        - site_page:
          text:
          url:
  config:
    edit_mode_only: false
    is_main: true
    id:
    aria_labelledby:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
