# Metadata about this component, to be used in the CMS
spec:
  structures:
    - place_topper
  label: "Topper - Place"
  description:
  icon: crown
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  heading:
  subheading:
  styles:
    vibe: down-to-business
    color_palette:
    enable_blend: false
    enable_pattern: false
    tint_opacity: 0.5
    margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: