# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Icon Bar"
  description: Horizontal icons with links.
  icon: view_week
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"
  items:
    - icon: book
      text: Text
      url:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: