# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Factoids"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: By the Numbers
  items:
    - pre:
      stat:
      post:
      source:
  config:
    edit_mode_only: false
  styles:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: