# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Button Group"
  description: A group of buttons.
  icon: buttons_alt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Button Group Heading
  body:
  buttons:
    - text: Call to Action
      url:
      icon: 
  postscript:
    copy:
    postscript_links:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  body:
    type: markdown
  postscript:
    type: markdown